# use the dockerfile provided at root, this is only for development purposes and will be deleted
version: '3.9'
services:
  mysql:
    restart: unless-stopped
    container_name: oc_mysql
    platform: linux/x86_64
    image: "mysql:8"
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openchat
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: "exit 0"
    networks:
      - openchat_network

  qdrant:
    image: qdrant/qdrant
    container_name: oc_qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - openchat_network

  nginx:
    image: nginx
    container_name: oc_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem
      - ./nginx/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
      - ./static:/app/web/static/
    networks:
      - openchat_network
    env_file:
      - .env
    depends_on:
      - qdrant
      - mysql
      - web
      - redis
      - celery_worker

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oc_web
    ports:
      - "8001:8000"
    volumes:
      - ./website_data_sources:/app/website_data_sources
      - ./:/app/
    # - ./entrypoint.sh:/app/entrypoint.sh
    # - ./llama-2-7b-chat.ggmlv3.q4_K_M.bin:/app/llama-2-7b-chat.ggmlv3.q4_K_M.bin:ro
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: [ "/entrypoint.sh" ]
    command: >
      sh -c "python manage.py migrate auth && 
             python manage.py migrate && 
             python manage.py create_superuser &&
             python manage.py sync_models &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - openchat_network

  adminer:
    image: adminer
    container_name: oc_adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db # Change this to match your database server name
    depends_on:
      - mysql
    networks:
      - openchat_network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oc_celery
    volumes:
      - ./website_data_sources:/app/website_data_sources
      - ./:/app/
      # - ./llama-2-7b-chat.ggmlv3.q4_K_M.bin:/app/llama-2-7b-chat.ggmlv3.q4_K_M.bin:ro
    depends_on:
      - web
    env_file:
      - .env
    command: celery -A dj_backend_server worker --loglevel=info
    networks:
      - openchat_network

  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: oc_redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - openchat_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  openchat_network:


volumes:
  qdrant_storage:
  database:
  redis_data:
